---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution_version ==  "Ubuntu"

  - name: install apache2 and php package for Ubuntu
    apt:
      name: 
        -  apache2
        -  php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 add php package support for CentOS
    dnf:
      name:
        -  httpd
        -  php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
