---

- name: Manage web servers
  hosts: web_servers
  become: true
  tasks:
    - name: Install updates for CentOS
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Update repository index for Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache2 and PHP for Ubuntu
      apt:
        name:
          - mariadb-server
          - apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy default html file for site
      tags: apache,apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: Install Apache2 and PHP for CentOS
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"


    - name: Install unzip
      package:
        name: unzip
        state: present

    - name: Download Terraform ZIP file
      get_url:
        url: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /tmp/terraform_0.12.28_linux_amd64.zip

    - name: Unarchive Terraform ZIP file
      unarchive:
        src: /tmp/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

