---
- name: Gather and debug facts
  hosts: all
  tasks:
    - name: Show hostname and OS
      debug:
        msg:
          - "Hostname: {{ ansible_hostname }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
