---
- name: Using handlers
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      package:  # Use 'package' for cross-distro compatibility
        name: nginx
        state: present
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes  # Ensures Nginx starts at boot
