---
- name: Create users on multiple operating systems
  hosts: all
  become: true
  vars:
    new_users:
      - username: KumsaMergia
        shell: /bin/bash
      - username: ChristinoRonalodo
        shell: /bin/bash

  tasks:
    - name: Create users
      user:
        name: "{{ item.username }}"
        shell: "{{ item.shell }}"
        state: present
      loop: "{{ new_users }}"
