---
- name: Remove and update packages on remote machine
  hosts: all
  become: true
  vars:
    packages_to_remove:
      - vim

  tasks:
    - name: Remove packages
      package:
        name: "{{ packages_to_remove }}"
        state: absent

    - name: Update all packages
      package:
        name: "*"
        state: latest
