---
# Ansible playbook to create LVM physical volumes, a volume group, a logical volume, and a filesystem, then mount it.

- name: Create LVM Physical Volumes, Volume Group, Logical Volume, and Filesystem
  hosts: all                # The playbook applies to all hosts in the inventory.
  become: true              # Run tasks with elevated privileges (sudo).
  vars:
    lvm_vg: "Kumsa_VolumeG" # Name of the volume group to be created.
    lvm_lv: "Kumsa_LogicalV" # Name of the logical volume to be created.
    lvm_size: "8G"          # Size of the logical volume.
    fs_type: "ext4"         # Filesystem type to create on the logical volume.
    devices:                # List of devices to use for physical volumes.
      - {name: "/dev/sdb"}  # First device for the physical volume.
      - {name: "/dev/sdc"}  # Second device for the physical volume.
    mount_point: "/mnt/KuData" # Directory where the logical volume will be mounted.

  tasks:
    - name: Create physical volumes
      command: pvcreate {{ item.name }} # Creates physical volumes on each device.
      loop: "{{ devices }}"             # Loops through all devices in the `devices` list.
      notify:                           # Trigger handler after creating physical volumes.
        - Verify Physical Volumes

    - name: Create Volume Group
      command: vgcreate {{ lvm_vg }} {{ devices | map(attribute='name') | join(' ') }}
      # Creates a volume group named `lvm_vg` using all devices.
      notify:                           # Trigger handler after creating the volume group.
        - Verify Volume Group

    - name: Create Logical Volume
      command: lvcreate -L {{ lvm_size }} -n {{ lvm_lv }} {{ lvm_vg }}
      # Creates a logical volume named `lvm_lv` of size `lvm_size` in volume group `lvm_vg`.
      notify:                           # Trigger handler after creating the logical volume.
        - Verify Logical Volume

    - name: Create filesystem on Logical Volume
      command: mkfs -t {{ fs_type }} /dev/{{ lvm_vg }}/{{ lvm_lv }}
      # Creates a filesystem of type `fs_type` on the logical volume.
      notify:                           # Trigger handler after creating the filesystem.
        - Verify Filesystem

    - name: Create mount point directory
      file:
        path: "{{ mount_point }}"       # Path of the mount point.
        state: directory                # Ensures the directory exists.

    - name: Mount Logical Volume
      mount:
        path: "{{ mount_point }}"       # Mount point for the logical volume.
        src: "/dev/{{ lvm_vg }}/{{ lvm_lv }}" # Logical volume to mount.
        fstype: "{{ fs_type }}"         # Filesystem type to use for mounting.
        state: mounted                  # Ensures the logical volume is mounted.

  handlers:
    - name: Verify Physical Volumes
      command: pvdisplay                # Displays details of all physical volumes.
      become: true                      # Runs with elevated privileges.

    - name: Verify Volume Group
      command: vgs {{ lvm_vg }}         # Displays details of the volume group.
      become: true                      # Runs with elevated privileges.

    - name: Verify Logical Volume
      command: lvdisplay /dev/{{ lvm_vg }}/{{ lvm_lv }}
      # Displays details of the specified logical volume.
      become: true                      # Runs with elevated privileges.

    - name: Verify Filesystem
      command: lsblk /dev/{{ lvm_vg }}/{{ lvm_lv }}
      # Displays block device details for the logical volume.
      become: true                      # Runs with elevated privileges.
